// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAldx211e5AP2vKCr6ZC3K2BV7jP7EyZ10',
    appId: '1:573263637693:web:a41755d95d84f97fbb9bd4',
    messagingSenderId: '573263637693',
    projectId: 'stock-fd9a6',
    authDomain: 'stock-fd9a6.firebaseapp.com',
    storageBucket: 'stock-fd9a6.appspot.com',
    measurementId: 'G-5MYFKXKQST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4OhpuKywoIe207CtSi-VWKYVtFTe9cRM',
    appId: '1:573263637693:android:b1c0d05b1dbb114cbb9bd4',
    messagingSenderId: '573263637693',
    projectId: 'stock-fd9a6',
    storageBucket: 'stock-fd9a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Tsw-DqaG4c4DEjNygyOUCpDsl8rfmjA',
    appId: '1:573263637693:ios:8f95d4d62bca1f95bb9bd4',
    messagingSenderId: '573263637693',
    projectId: 'stock-fd9a6',
    storageBucket: 'stock-fd9a6.appspot.com',
    iosClientId: '573263637693-n1mbn7gdim02bsjt8c94p70vpv89t4gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.stock2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Tsw-DqaG4c4DEjNygyOUCpDsl8rfmjA',
    appId: '1:573263637693:ios:8f95d4d62bca1f95bb9bd4',
    messagingSenderId: '573263637693',
    projectId: 'stock-fd9a6',
    storageBucket: 'stock-fd9a6.appspot.com',
    iosClientId: '573263637693-n1mbn7gdim02bsjt8c94p70vpv89t4gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.stock2',
  );
}
